# Site settings
title: UndeadFred
email: fhhopkinson@gmail.com
url: https://www.undeadfred.co.uk
description: "This brilliant site depicts its creator in a wonderful light portraying him as a warrior savant."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '000000'
  links: '#219ab3'

# Footer settings
footer: Undead<i class="fa fa-heartbeat" aria-hidden="true">Fred</i>

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: uk.linkedin.com/in/fhhopkinson
  - title: github
    url: https://github.com/fhhopkinson

# Build settings
markdown: kramdown
permalink: pretty
