# Site settings
title: Profile
email: fhhopkinson@gmail.com
url: https://www.undeadfred.co.uk
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Undead<i class="fa fa-heartbeat" aria-hidden="true"></i>Fred

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: uk.linkedin.com/in/fhhopkinson
  - title: github
    url: https://github.com/fhhopkinson

# Build settings
markdown: kramdown
permalink: pretty
